
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND AT COLON COMMA DOT FIELD FROM IP_ADDRESS MAC_ADDRESS NUMBER OPERATOR OR TO VALUE WHEREstatement : FROM endpoint TO endpoint\n                 | FROM endpoint TO endpoint where_clause\n    endpoint : IP_ADDRESS COLON NUMBER\n    \n    endpoint : IP_ADDRESS AT MAC_ADDRESS\n    \n    endpoint : IP_ADDRESS COLON NUMBER AT MAC_ADDRESS\n    \n    endpoint : IP_ADDRESS\n    \n    endpoint : MAC_ADDRESS\n    \n    condition : FIELD OPERATOR VALUE\n                | FIELD OPERATOR NUMBER\n    \n    condition_list : condition \n                    | condition_list COMMA condition\n    \n    where_clause : WHERE condition_list\n    '
    
_lr_action_items = {'FROM':([0,],[2,]),'$end':([1,4,5,9,10,11,12,15,16,18,21,22,23,],[0,-6,-7,-1,-3,-4,-2,-12,-10,-5,-11,-8,-9,]),'IP_ADDRESS':([2,6,],[4,4,]),'MAC_ADDRESS':([2,6,8,14,],[5,5,11,18,]),'TO':([3,4,5,10,11,18,],[6,-6,-7,-3,-4,-5,]),'COLON':([4,],[7,]),'AT':([4,10,],[8,14,]),'WHERE':([4,5,9,10,11,18,],[-6,-7,13,-3,-4,-5,]),'NUMBER':([7,20,],[10,23,]),'FIELD':([13,19,],[17,17,]),'COMMA':([15,16,21,22,23,],[19,-10,-11,-8,-9,]),'OPERATOR':([17,],[20,]),'VALUE':([20,],[22,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'endpoint':([2,6,],[3,9,]),'where_clause':([9,],[12,]),'condition_list':([13,],[15,]),'condition':([13,19,],[16,21,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> FROM endpoint TO endpoint','statement',4,'p_statement_root','parser.py',7),
  ('statement -> FROM endpoint TO endpoint where_clause','statement',5,'p_statement_root','parser.py',8),
  ('endpoint -> IP_ADDRESS COLON NUMBER','endpoint',3,'p_endpoint_ip_and_port','parser.py',17),
  ('endpoint -> IP_ADDRESS AT MAC_ADDRESS','endpoint',3,'p_endpoint_ip_and_mac','parser.py',24),
  ('endpoint -> IP_ADDRESS COLON NUMBER AT MAC_ADDRESS','endpoint',5,'p_endpoint_ip_port_and_mac','parser.py',31),
  ('endpoint -> IP_ADDRESS','endpoint',1,'p_endpoint_ip_only','parser.py',38),
  ('endpoint -> MAC_ADDRESS','endpoint',1,'p_endpoint_mac_only','parser.py',45),
  ('condition -> FIELD OPERATOR VALUE','condition',3,'p_condition','parser.py',52),
  ('condition -> FIELD OPERATOR NUMBER','condition',3,'p_condition','parser.py',53),
  ('condition_list -> condition','condition_list',1,'p_condition_list','parser.py',60),
  ('condition_list -> condition_list COMMA condition','condition_list',3,'p_condition_list','parser.py',61),
  ('where_clause -> WHERE condition_list','where_clause',2,'p_where_clause','parser.py',71),
]
